"""create initial logistics schema

Revision ID: a679f307284a
Revises: 
Create Date: 2026-08-07 14:30:19.432250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a679f307284a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('primary_email', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=30), nullable=False),
    sa.Column('client_type', sa.String(length=30), nullable=False),
    sa.Column('billing_address_line1', sa.String(length=150), nullable=False),
    sa.Column('billing_city', sa.String(length=100), nullable=False),
    sa.Column('billing_state', sa.String(length=100), nullable=True),
    sa.Column('billing_postal_code', sa.String(length=20), nullable=True),
    sa.Column('billing_country_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('primary_email')
    )
    op.create_table('facilities',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('facility_code', sa.String(length=10), nullable=False),
    sa.Column('facility_name', sa.String(length=150), nullable=False),
    sa.Column('facility_type', sa.String(length=100), nullable=False),
    sa.Column('address_line1', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('is_security_certified', sa.Boolean(), nullable=False),
    sa.Column('security_certification_level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('facility_id'),
    sa.UniqueConstraint('facility_code')
    )
    op.create_table('service_types',
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('max_delivery_hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('service_type_id')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=30), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('operational_status', sa.String(length=30), nullable=False),
    sa.Column('home_facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['home_facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('route_code', sa.String(length=30), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('standard_transit_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('origin_facility_id', sa.Integer(), nullable=False),
    sa.Column('destination_facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['origin_facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('route_id'),
    sa.UniqueConstraint('route_code')
    )
    op.create_table('shipment_bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('booking_status', sa.String(length=50), nullable=False),
    sa.Column('requires_pickup', sa.Boolean(), nullable=False),
    sa.Column('pickup_address_line1', sa.String(length=150), nullable=True),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('quoted_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quoted_currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sender_client_id', sa.Integer(), nullable=False),
    sa.Column('receiver_client_id', sa.Integer(), nullable=False),
    sa.Column('payer_client_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payer_client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['receiver_client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['sender_client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.service_type_id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vin_or_tail_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_volume_m3', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('operational_status', sa.String(length=30), nullable=False),
    sa.Column('home_facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['home_facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('vin_or_tail_number')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('payer_client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['shipment_bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['payer_client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('shipment_status', sa.String(length=50), nullable=False),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('origin_facility_id', sa.Integer(), nullable=False),
    sa.Column('destination_facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['shipment_bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['destination_facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['origin_facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('packages',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('package_code_epc', sa.String(length=100), nullable=False),
    sa.Column('actual_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('length_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('width_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('customs_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hazardous_materials_flag', sa.Boolean(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('package_code_epc')
    )
    op.create_table('transport_legs',
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('leg_number', sa.Integer(), nullable=False),
    sa.Column('leg_status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('leg_id')
    )
    op.create_table('package_facility_transits',
    sa.Column('transit_id', sa.Integer(), nullable=False),
    sa.Column('inbound_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outbound_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sorting_lane', sa.String(length=50), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.package_id'], ),
    sa.PrimaryKeyConstraint('transit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_facility_transits')
    op.drop_table('transport_legs')
    op.drop_table('packages')
    op.drop_table('shipments')
    op.drop_table('payments')
    op.drop_table('vehicles')
    op.drop_table('shipment_bookings')
    op.drop_table('routes')
    op.drop_table('drivers')
    op.drop_table('service_types')
    op.drop_table('facilities')
    op.drop_table('clients')
    # ### end Alembic commands ###
